_wandb:
    value:
        cli_version: 0.22.3
        e:
            5kw4klfj5v454jotmdlsv8z4bzy7izv7:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                codePath: /Users/Mohammad/Documents/ds-projects/deg-predict-demo/degradation-transformer/main.ipynb
                codePathLocal: main.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "280204685312"
                email: s.m.asadzade@gmail.com
                executable: /Users/Mohammad/miniconda3/envs/smartchp/bin/python
                git:
                    commit: 94d685ac7704103ff0eff89919964ec493e73b3e
                    remote: https://github.com/seyedasadzadeh/degradation-transformer.git
                host: MacBookAir.home
                memory:
                    total: "8589934592"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/Mohammad/Documents/ds-projects/deg-predict-demo/degradation-transformer/main.ipynb
                python: CPython 3.11.13
                root: /Users/Mohammad/Documents/ds-projects/deg-predict-demo/degradation-transformer
                startedAt: "2025-11-03T10:24:17.038947Z"
                writerId: 5kw4klfj5v454jotmdlsv8z4bzy7izv7
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.22.3
            "8":
                - 1
            "12": 0.22.3
            "13": darwin-arm64
context_window:
    value: 40
embedding_dim:
    value: 64
epochs:
    value: 1
learning_rate:
    value: 0.003
num_blocks:
    value: 3
num_heads:
    value: 8
vocab_size:
    value: 500
